#!/usr/bin/env python3
"""
generate_rules.py — Port whitelist rule generator for Wazuh
============================================================
Reads the wazuh.port_whitelist section from homelab-sentinel.yaml and
outputs merge-ready XML rule blocks for /var/ossec/etc/rules/local_rules.xml.

Self-contained — no imports from sentinel/ library.

Usage:
  python3 wazuh/generate_rules.py
  python3 wazuh/generate_rules.py --config /path/to/homelab-sentinel.yaml
  python3 wazuh/generate_rules.py > /tmp/port_rules.xml
"""

import argparse
import os
import sys
from xml.sax.saxutils import escape

import yaml

DEFAULT_CONFIG_PATHS = [
    "/etc/homelab-sentinel.yaml",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "homelab-sentinel.yaml"),
]

DEFAULTS = {
    "unexpected_port_level": 12,
    "expected_port_rule_level": 3,
    "base_rule_id": 100100,
    "catchall_rule_id": 100200,
    "rule_id_step": 10,
}


def load_config(config_path: str | None) -> dict:
    """Load YAML config and return the wazuh section."""
    paths = [config_path] if config_path else DEFAULT_CONFIG_PATHS
    for path in paths:
        try:
            with open(path) as f:
                data = yaml.safe_load(f) or {}
                return data.get("wazuh", {})
        except (FileNotFoundError, PermissionError):
            continue
    print("Error: no config file found. Searched:", file=sys.stderr)
    for p in paths:
        print(f"  {p}", file=sys.stderr)
    sys.exit(1)


def generate_rules(wazuh_cfg: dict) -> str:
    """Generate XML rule blocks from the wazuh config section."""
    whitelist = wazuh_cfg.get("port_whitelist", {})
    expected_level = wazuh_cfg.get("expected_port_rule_level", DEFAULTS["expected_port_rule_level"])
    unexpected_level = wazuh_cfg.get("unexpected_port_level", DEFAULTS["unexpected_port_level"])
    base_id = wazuh_cfg.get("base_rule_id", DEFAULTS["base_rule_id"])
    catchall_id = wazuh_cfg.get("catchall_rule_id", DEFAULTS["catchall_rule_id"])
    step = wazuh_cfg.get("rule_id_step", DEFAULTS["rule_id_step"])

    lines: list[str] = []
    lines.append("<!-- ═══ BEGIN homelab-sentinel generated port rules ═══ -->")
    lines.append("<!-- Generated by wazuh/generate_rules.py — do not edit by hand -->")
    lines.append(f"<!-- Rule ID range: {base_id}-{catchall_id} -->")
    lines.append("")

    rule_id = base_id
    for agent, ports in whitelist.items():
        if not ports:
            continue

        # Build comment block listing ports and services
        lines.append(f"  <!-- {escape(agent)} expected ports -->")
        lines.append("  <!--")
        for entry in ports:
            port = entry.get("port", "?")
            service = entry.get("service", "")
            proto = entry.get("proto", "tcp")
            lines.append(f"    {port}/{proto} — {escape(service)}")
        lines.append("  -->")

        # Build match pattern from port numbers
        port_numbers = [str(entry["port"]) for entry in ports if "port" in entry]
        match_pattern = "|".join(port_numbers)

        lines.append(f'  <rule id="{rule_id}" level="{expected_level}">')
        lines.append("    <if_sid>533</if_sid>")
        lines.append(f"    <hostname>{escape(agent)}</hostname>")
        lines.append(f"    <match>{escape(match_pattern)}</match>")
        lines.append(f"    <description>Expected port change on {escape(agent)} — whitelisted</description>")
        lines.append("  </rule>")
        lines.append("")

        rule_id += step

        if rule_id >= catchall_id:
            print(
                f"Warning: rule IDs reached catch-all ID {catchall_id}. "
                f"Increase catchall_rule_id or reduce rule_id_step.",
                file=sys.stderr,
            )
            break

    # Catch-all rule for unexpected port changes
    lines.append("  <!-- Catch-all: unexpected port changes -->")
    lines.append(f'  <rule id="{catchall_id}" level="{unexpected_level}">')
    lines.append("    <if_sid>533</if_sid>")
    lines.append("    <description>Unexpected port change — not in whitelist</description>")
    lines.append("  </rule>")
    lines.append("")
    lines.append("<!-- ═══ END homelab-sentinel generated port rules ═══ -->")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Wazuh port whitelist rules from homelab-sentinel.yaml")
    parser.add_argument("--config", "-c", help="Path to homelab-sentinel.yaml (default: auto-detect)")
    args = parser.parse_args()

    wazuh_cfg = load_config(args.config)
    print(generate_rules(wazuh_cfg))


if __name__ == "__main__":
    main()
